version: '3'

services:
  myapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    depends_on:
      - redis
      - mycelery
    networks:
      - mynetwork
    volumes:
      - ${PWD}/videos

  redis:
    image: 'redis:5'
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  mycelery:
    build: .
    command: celery -A task worker --loglevel=info
    depends_on:
      - redis
    networks:
      - mynetwork

  mycelerybeat:
    build: .
    command: celery -A task beat --loglevel=info
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
